### ISSUE TITLE
Improve OCR detection

### ISSUE THREAD

**Issue by Apolloden** [swighCode/PhotoMid#22]
At the moment the optical character recognition is not reliable. It has a 0% chance of detecting handwritten text and it's even struggling with computer-written text with a font standard.

I have found that this setting works most of the time:
- Font: Calibri
- Size: 18
- Color: black
- Background: white

This is done on a 1500x800px sheet in Paint.

We should experiment with OpenCv and Tesseract to improve its reading.

**Comment by swighCode** [comment]
This can only realistically be done with additional training data. We might do this later but not now.
